In [32]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

## Data preparation

In [33]:
df = pd.read_csv('./03-classification/lead-scoring-dataset-2026.csv')

In [34]:
df.head()

,lead_source,industry,employment_status,location,annual_income,number_of_courses_viewed,interaction_count,lead_score,converted
0,organic_search,technology,employed,europe,88160.0,3,4,0.64,1
1,social_media,technology,employed,south_america,72688.0,3,7,0.72,1
2,referral,retail,employed,europe,44697.0,3,4,0.58,1
3,paid_ads,manufacturing,student,NaN,NaN,3,6,0.57,0
4,referral,manufacturing,student,north_america,24062.0,4,5,0.62,1

In [35]:
df.dtypes

lead_source                     str
industry                        str
employment_status               str
location                        str
annual_income               float64
number_of_courses_viewed      int64
interaction_count             int64
lead_score                  float64
converted                     int64
dtype: object

In [36]:
categorical = list(df.dtypes[df.dtypes == 'str'].index)
numerical = ['annual_income', 'number_of_courses_viewed', 'interaction_count', 'lead_score']
target = 'converted'

In [37]:
df.isnull().sum()

lead_source                 148
industry                    240
employment_status           194
location                    208
annual_income               369
number_of_courses_viewed      0
interaction_count             0
lead_score                   35
converted                     0
dtype: int64

In [38]:
df[categorical] = df[categorical].fillna('NA')
df[numerical] = df[numerical].fillna(0.0)

In [39]:
df.head()

,lead_source,industry,employment_status,location,annual_income,number_of_courses_viewed,interaction_count,lead_score,converted
0,organic_search,technology,employed,europe,88160.0,3,4,0.64,1
1,social_media,technology,employed,south_america,72688.0,3,7,0.72,1
2,referral,retail,employed,europe,44697.0,3,4,0.58,1
3,paid_ads,manufacturing,student,NA,0.0,3,6,0.57,0
4,referral,manufacturing,student,north_america,24062.0,4,5,0.62,1

## Validation framework

In [40]:
df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=1)

In [41]:
df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=1)

In [42]:
print(f"# rows: {len(df)}")
print(f"# train rows: {len(df_train)}")
print(f"# val rows: {len(df_val)}")
print(f"# test rows: {len(df_test)}")

# rows: 5000
# train rows: 3000
# val rows: 1000
# test rows: 1000

In [43]:
df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)
df_full_train = df_full_train.reset_index(drop=True)

In [45]:
df_train.head()

,lead_source,industry,employment_status,location,annual_income,number_of_courses_viewed,interaction_count,lead_score,converted
0,paid_ads,technology,employed,asia,80198.0,5,9,0.91,1
1,paid_ads,retail,employed,asia,50548.0,2,5,0.48,0
2,NA,finance,employed,NA,76300.0,0,3,0.42,0
3,paid_ads,finance,employed,NA,80371.0,2,6,0.49,0
4,organic_search,finance,employed,asia,73567.0,2,4,0.48,1

In [47]:
y_train = df_train[target].values
y_val = df_val[target].values
y_test = df_test[target].values

In [49]:
del df_train[target]
del df_val[target]
del df_test[target]

### EDA

### Q.1
What is the most frequent observation (mode) for the column `industry`?

- `NA`
- `technology` $\checkmark$
- `healthcare`
- `retail`

In [50]:
df_full_train['industry'].value_counts()

industry
technology       955
retail           742
healthcare       661
finance          569
education        496
manufacturing    377
NA               200
Name: count, dtype: int64