# Churn Project

## Data preparation

In [135]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

In [136]:
# data = 'https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-03-churn-prediction/WA_Fn-UseC_-Telco-Customer-Churn.csv'

# !wget $data -O ./03-classification/data-week-3.csv

In [137]:
df = pd.read_csv('./03-classification/data-week-3.csv')

In [138]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [139]:
df.head().T

,0,1,2,3,4
customerID,7590-VHVEG,5575-GNVDE,3668-QPYBK,7795-CFOCW,9237-HQITU
gender,Female,Male,Male,Male,Female
SeniorCitizen,0,0,0,0,0
Partner,Yes,No,No,No,No
Dependents,No,No,No,No,No
tenure,1,34,2,45,2
PhoneService,No,Yes,Yes,No,Yes
MultipleLines,No phone service,No,No,No phone service,No
InternetService,DSL,DSL,DSL,DSL,Fiber optic
OnlineSecurity,No,Yes,Yes,Yes,No
OnlineBackup,Yes,No,Yes,No,No
DeviceProtection,No,Yes,No,Yes,No
TechSupport,No,No,No,Yes,No
StreamingTV,No,No,No,No,No
StreamingMovies,No,No,No,No,No
Contract,Month-to-month,One year,Month-to-month,One year,Month-to-month
PaperlessBilling,Yes,No,Yes,No,Yes
PaymentMethod,Electronic check,Mailed check,Mailed check,Bank transfer (automatic),Electronic check
MonthlyCharges,29.85,56.95,53.85,42.3,70.7
TotalCharges,29.85,1889.5,108.15,1840.75,151.65
Churn,No,No,Yes,No,Yes

In [140]:
df.columns = df.columns.str.lower().str.replace(' ', '_')

In [141]:
categorical_columns = list(df.dtypes[df.dtypes == 'str'].index)

for col in categorical_columns:
    df[col] = df[col].str.lower().str.replace(' ', '_')

In [142]:
df.head().T

,0,1,2,3,4
customerid,7590-vhveg,5575-gnvde,3668-qpybk,7795-cfocw,9237-hqitu
gender,female,male,male,male,female
seniorcitizen,0,0,0,0,0
partner,yes,no,no,no,no
dependents,no,no,no,no,no
tenure,1,34,2,45,2
phoneservice,no,yes,yes,no,yes
multiplelines,no_phone_service,no,no,no_phone_service,no
internetservice,dsl,dsl,dsl,dsl,fiber_optic
onlinesecurity,no,yes,yes,yes,no
onlinebackup,yes,no,yes,no,no
deviceprotection,no,yes,no,yes,no
techsupport,no,no,no,yes,no
streamingtv,no,no,no,no,no
streamingmovies,no,no,no,no,no
contract,month-to-month,one_year,month-to-month,one_year,month-to-month
paperlessbilling,yes,no,yes,no,yes
paymentmethod,electronic_check,mailed_check,mailed_check,bank_transfer_(automatic),electronic_check
monthlycharges,29.85,56.95,53.85,42.3,70.7
totalcharges,29.85,1889.5,108.15,1840.75,151.65
churn,no,no,yes,no,yes

In [143]:
df.dtypes

customerid              str
gender                  str
seniorcitizen         int64
partner                 str
dependents              str
tenure                int64
phoneservice            str
multiplelines           str
internetservice         str
onlinesecurity          str
onlinebackup            str
deviceprotection        str
techsupport             str
streamingtv             str
streamingmovies         str
contract                str
paperlessbilling        str
paymentmethod           str
monthlycharges      float64
totalcharges            str
churn                   str
dtype: object

In [144]:
df.seniorcitizen.unique() # categorical

array([0, 1])

In [145]:
df.totalcharges.unique()[:5] # numerical

<StringArray>
['29.85', '1889.5', '108.15', '1840.75', '151.65']
Length: 5, dtype: str

In [146]:
# pd.to_numeric(df.totalcharges)

```console
ValueError: Unable to parse string "_" at position 488

In [147]:
tc = pd.to_numeric(df.totalcharges, errors='coerce')

In [148]:
tc.isnull().sum()

np.int64(11)

In [149]:
df[tc.isnull()][['customerid', 'tenure', 'totalcharges']]

      customerid  tenure totalcharges
488   4472-lvygi       0            _
753   3115-czmzd       0            _
936   5709-lvoeq       0            _
1082  4367-nuyao       0            _
1340  1371-dwpaz       0            _
3331  7644-omvmy       0            _
3826  3213-vvolg       0            _
4380  2520-sgtta       0            _
5218  2923-arzlg       0            _
6670  4075-wkniu       0            _
6754  2775-sefee       0            _

In [150]:
df.totalcharges = pd.to_numeric(df.totalcharges, errors='coerce')
df.totalcharges = df.totalcharges.fillna(0)

In [151]:
df.isnull().sum()

customerid          0
gender              0
seniorcitizen       0
partner             0
dependents          0
tenure              0
phoneservice        0
multiplelines       0
internetservice     0
onlinesecurity      0
onlinebackup        0
deviceprotection    0
techsupport         0
streamingtv         0
streamingmovies     0
contract            0
paperlessbilling    0
paymentmethod       0
monthlycharges      0
totalcharges        0
churn               0
dtype: int64

In [152]:
df.churn.head()

0     no
1     no
2    yes
3     no
4    yes
Name: churn, dtype: str

In [153]:
df.churn = (df.churn.values == 'yes').astype('int')

In [154]:
df.head(3).T

                                 0             1               2
customerid              7590-vhveg    5575-gnvde      3668-qpybk
gender                      female          male            male
seniorcitizen                    0             0               0
partner                        yes            no              no
dependents                      no            no              no
tenure                           1            34               2
phoneservice                    no           yes             yes
multiplelines     no_phone_service            no              no
internetservice                dsl           dsl             dsl
onlinesecurity                  no           yes             yes
onlinebackup                   yes            no             yes
deviceprotection                no           yes              no
techsupport                     no            no              no
streamingtv                     no            no              no
streamingmovies                 no            no              no
contract            month-to-month      one_year  month-to-month
paperlessbilling               yes            no             yes
paymentmethod     electronic_check  mailed_check    mailed_check
monthlycharges               29.85         56.95           53.85
totalcharges                 29.85        1889.5          108.15
churn                            0             0               1

## Validation

In [155]:
from sklearn.model_selection import train_test_split

In [156]:
df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=1)

$
\boxed{r = \frac{p}{1-q}}
$

Where:

- $p$: Desired proportion of the total dataset.
- $q$: Proportion excluded in the first split.
- $r$: Proportion to split from the remaining data.

$
\rightarrow\frac{20\%}{80\%} = 25\%
$

In [157]:
df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=1)

In [158]:
len(df_train), len(df_val), len(df_test)

(4225, 1409, 1409)

In [159]:
df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

In [160]:
y_train = df_train.churn.values
y_val = df_val.churn.values
y_test = df_test.churn.values

In [161]:
del df_train['churn']
del df_val['churn']
del df_test['churn']

## EDA

In [162]:
df_full_train = df_full_train.reset_index(drop=True)

In [163]:
df_full_train.isnull().sum()

customerid          0
gender              0
seniorcitizen       0
partner             0
dependents          0
tenure              0
phoneservice        0
multiplelines       0
internetservice     0
onlinesecurity      0
onlinebackup        0
deviceprotection    0
techsupport         0
streamingtv         0
streamingmovies     0
contract            0
paperlessbilling    0
paymentmethod       0
monthlycharges      0
totalcharges        0
churn               0
dtype: int64

In [164]:
df_full_train.churn.value_counts()

churn
0    4113
1    1521
Name: count, dtype: int64

In [165]:
df_full_train.churn.value_counts(normalize=True)

churn
0    0.730032
1    0.269968
Name: proportion, dtype: float64

In [166]:
1521/(1521+4113) # churn rate

0.26996805111821087

The mean of a binary column is the number of ones divided by the total number of rows, which is exactly the churn rate

$$
\mathbf{y} =
\begin{bmatrix}
y_1 & y_2 & \cdots & y_N
\end{bmatrix}^{\top},
\qquad
\text{Churn Rate}
= \frac{1}{N}\sum_{i=1}^{N} y_i
$$

$$
\mathbf{y} =
\begin{bmatrix}
1 & 0 & 1 & 1 & 0 & \cdots & 1
\end{bmatrix}^{\top}
$$

$$
\text{Churn Rate}
=
\frac{\displaystyle\sum_{i=1}^{N} y_i}
     {\displaystyle N}
=
\frac{\text{Number of ones}}
     {\text{Number of ones}+\text{Number of zeros}}
$$

In [167]:
df_full_train.churn.mean()

np.float64(0.26996805111821087)

In [168]:
df_full_train.head(2).T

                                    0                        1
customerid                 5442-pptjy               6261-rcvns
gender                           male                   female
seniorcitizen                       0                        0
partner                           yes                       no
dependents                        yes                       no
tenure                             12                       42
phoneservice                      yes                      yes
multiplelines                      no                       no
internetservice                    no                      dsl
onlinesecurity    no_internet_service                      yes
onlinebackup      no_internet_service                      yes
deviceprotection  no_internet_service                      yes
techsupport       no_internet_service                      yes
streamingtv       no_internet_service                       no
streamingmovies   no_internet_service                      yes
contract                     two_year                 one_year
paperlessbilling                   no                       no
paymentmethod            mailed_check  credit_card_(automatic)
monthlycharges                   19.7                     73.9
totalcharges                   258.35                  3160.55
churn                               0                        1

In [169]:
df_full_train.seniorcitizen.unique() # categorical column

array([0, 1])

In [170]:
numerical = ['tenure', 'monthlycharges', 'totalcharges']

In [171]:
categorical = [
    'gender',
    'seniorcitizen',
    'partner',
    'dependents',
    'phoneservice',
    'multiplelines',
    'internetservice',
    'onlinesecurity',
    'onlinebackup',
    'deviceprotection',
    'techsupport',
    'streamingtv',
    'streamingmovies',
    'contract',
    'paperlessbilling',
    'paymentmethod',
]

In [172]:
df_full_train[categorical].nunique()

gender              2
seniorcitizen       2
partner             2
dependents          2
phoneservice        2
multiplelines       3
internetservice     3
onlinesecurity      3
onlinebackup        3
deviceprotection    3
techsupport         3
streamingtv         3
streamingmovies     3
contract            3
paperlessbilling    2
paymentmethod       4
dtype: int64

## Risk

In [173]:
global_churn = df_full_train.churn.mean()

In [174]:
global_churn

np.float64(0.26996805111821087)

In [175]:
churn_female = df_full_train[df_full_train.gender == 'female'].churn.mean()
churn_male = df_full_train[df_full_train.gender == 'male'].churn.mean()

In [176]:
churn_female, churn_male

(np.float64(0.27682403433476394), np.float64(0.2632135306553911))

gender is probably not an important feature

In [177]:
global_churn - churn_female

np.float64(-0.006855983216553063)

In [178]:
global_churn - churn_male

np.float64(0.006754520462819769)

In [179]:
df_full_train.partner.value_counts()

partner
no     2932
yes    2702
Name: count, dtype: int64

In [180]:
churn_partner = df_full_train[df_full_train.partner == 'yes'].churn.mean()
churn_no_partner = df_full_train[df_full_train.partner == 'no'].churn.mean()

In [181]:
churn_partner, churn_no_partner

(np.float64(0.20503330866025166), np.float64(0.3298090040927694))

single customers are much more likely to churn

In [182]:
global_churn - churn_partner

np.float64(0.06493474245795922)

In [183]:
global_churn - churn_no_partner

np.float64(-0.05984095297455855)

### Feature Importance

#### Difference

$
R_{\text{global}} - R_{\text{group}} > 0 \longrightarrow R_{\text{global}} > R_{\text{group}}
$
- less likley to churn

$
R_{\text{global}} - R_{\text{group}} < 0 \longrightarrow R_{\text{global}} < R_{\text{group}}
$
- more likely to churn

$
\left|R_{\text{global}} - R_{\text{group}}\right|
\;\uparrow
\quad\Longrightarrow\quad
\text{Variable Importance}
\;\uparrow
$

#### Risk Ratio

$
\frac{\text{group}}{\text{global}} < 1
$
- less likeley to churn

$
\frac{\text{group}}{\text{global}} > 1
$
- more likeley to churn

$
\frac{\text{group}}{\text{global}} = 1
$
- the group is as likely to churn as everyone else

In [184]:
churn_no_partner/global_churn

np.float64(1.2216593879412643)

In [185]:
churn_partner/global_churn

np.float64(0.7594724924338315)

In [186]:
((churn_no_partner - global_churn)/global_churn)*100

np.float64(22.16593879412642)

- Customers without a partner churn 22% more often than the average customer.

```sql
SELECT
    gender,
    AVG(churn),
    AVG(churn) - global_churn AS diff,
    AVG(churn) / global_churn AS risk
FROM
    data
GROUP BY
    gender;

In [187]:
from IPython.display import display

for c in categorical:
    print(c)
    df_group = df_full_train.groupby(c).churn.agg(['mean', 'count'])
    df_group['diff'] = df_group['mean'] - global_churn # positive diff means the group churns more than average
    df_group['risk'] = df_group['mean'] / global_churn
    display(df_group)
    print()
    print()

gender

            mean  count      diff      risk
gender
female  0.276824   2796  0.006856  1.025396
male    0.263214   2838 -0.006755  0.974980

seniorcitizen

                   mean  count      diff      risk
seniorcitizen
0              0.242270   4722 -0.027698  0.897403
1              0.413377    912  0.143409  1.531208

partner

             mean  count      diff      risk
partner
no       0.329809   2932  0.059841  1.221659
yes      0.205033   2702 -0.064935  0.759472

dependents

                mean  count      diff      risk
dependents
no          0.313760   3968  0.043792  1.162212
yes         0.165666   1666 -0.104302  0.613651

phoneservice

                  mean  count      diff      risk
phoneservice
no            0.241316    547 -0.028652  0.893870
yes           0.273049   5087  0.003081  1.011412

multiplelines

                      mean  count      diff      risk
multiplelines
no                0.257407   2700 -0.012561  0.953474
no_phone_service  0.241316    547 -0.028652  0.893870
yes               0.290742   2387  0.020773  1.076948

internetservice

                     mean  count      diff      risk
internetservice
dsl              0.192347   1934 -0.077621  0.712482
fiber_optic      0.425171   2479  0.155203  1.574895
no               0.077805   1221 -0.192163  0.288201

onlinesecurity

                         mean  count      diff      risk
onlinesecurity
no                   0.420921   2801  0.150953  1.559152
no_internet_service  0.077805   1221 -0.192163  0.288201
yes                  0.153226   1612 -0.116742  0.567570

onlinebackup

                         mean  count      diff      risk
onlinebackup
no                   0.404323   2498  0.134355  1.497672
no_internet_service  0.077805   1221 -0.192163  0.288201
yes                  0.217232   1915 -0.052736  0.804660

deviceprotection

                         mean  count      diff      risk
deviceprotection
no                   0.395875   2473  0.125907  1.466379
no_internet_service  0.077805   1221 -0.192163  0.288201
yes                  0.230412   1940 -0.039556  0.853480

techsupport

                         mean  count      diff      risk
techsupport
no                   0.418914   2781  0.148946  1.551717
no_internet_service  0.077805   1221 -0.192163  0.288201
yes                  0.159926   1632 -0.110042  0.592390

streamingtv

                         mean  count      diff      risk
streamingtv
no                   0.342832   2246  0.072864  1.269897
no_internet_service  0.077805   1221 -0.192163  0.288201
yes                  0.302723   2167  0.032755  1.121328

streamingmovies

                         mean  count      diff      risk
streamingmovies
no                   0.338906   2213  0.068938  1.255358
no_internet_service  0.077805   1221 -0.192163  0.288201
yes                  0.307273   2200  0.037305  1.138182

contract

                    mean  count      diff      risk
contract
month-to-month  0.431701   3104  0.161733  1.599082
one_year        0.120573   1186 -0.149395  0.446621
two_year        0.028274   1344 -0.241694  0.104730

paperlessbilling

                      mean  count      diff      risk
paperlessbilling
no                0.172071   2313 -0.097897  0.637375
yes               0.338151   3321  0.068183  1.252560

paymentmethod

                               mean  count      diff      risk
paymentmethod
bank_transfer_(automatic)  0.168171   1219 -0.101797  0.622928
credit_card_(automatic)    0.164339   1217 -0.105630  0.608733
electronic_check           0.455890   1893  0.185922  1.688682
mailed_check               0.193870   1305 -0.076098  0.718121

## Mutual Information

- Mutual information measures the importance of categorical variables

In [188]:
from sklearn.metrics import mutual_info_score

In [189]:
mutual_info_score(df_full_train.churn, df_full_train.contract)

0.0983203874041556

In [190]:
mutual_info_score(df_full_train.churn, df_full_train.gender)

0.0001174846211139946

In [191]:
mutual_info_score(df_full_train.churn, df_full_train.gender)

0.0001174846211139946

In [192]:
mutual_info_score(df_full_train.churn, df_full_train.partner)

0.009967689095399745

`mutual_info_score` takes two arguments, while pandas apply passes one series at a time - so we wrap it in a function of one argument

In [193]:
def mutual_info_churn_score(series):
    return mutual_info_score(series, df_full_train.churn)

In [194]:
mi = df_full_train[categorical].apply(mutual_info_churn_score)
mi.sort_values(ascending=False).to_frame(name='mutual info score')

                  mutual info score
contract                   0.098320
onlinesecurity             0.063085
techsupport                0.061032
internetservice            0.055868
onlinebackup               0.046923
deviceprotection           0.043453
paymentmethod              0.043210
streamingtv                0.031853
streamingmovies            0.031581
paperlessbilling           0.017589
dependents                 0.012346
partner                    0.009968
seniorcitizen              0.009410
multiplelines              0.000857
phoneservice               0.000229
gender                     0.000117

## Correlation Coefficient

- it tells us how strongly each numerical feature is related to churn

$
-1 \leq r \leq 1
$

$
\underbrace{\operatorname{sign}(r)}_{\text{Direction}}
\qquad
\underbrace{|r|}_{\text{Strength}}
$

$
|r| \uparrow
\quad\Longrightarrow\quad
\text{Correlation Strength} \uparrow
$

$
\begin{aligned}
0 \leq |r| < 0.2
&\quad \Rightarrow \quad \text{LOW} \\[6pt]
0.2 \leq |r| < 0.5
&\quad \Rightarrow \quad \text{MEDIUM} \\[6pt]
0.5 \leq |r| \leq 1
&\quad \Rightarrow \quad \text{STRONG}
\end{aligned}
$

In [195]:
df_full_train[numerical].corrwith(df_full_train.churn)

tenure           -0.351885
monthlycharges    0.196805
totalcharges     -0.196353
dtype: float64

- Tenure has a medium negative correlation. The longer customers stay with the company, the less likely they are to churn.

In [196]:
df_full_train[numerical].corrwith(df_full_train.churn).abs()

tenure            0.351885
monthlycharges    0.196805
totalcharges      0.196353
dtype: float64

- Tenure is the most important numerical feature.

In [197]:
df_full_train.tenure.max()

np.int64(72)

In [198]:
df_full_train[df_full_train.tenure <= 2].churn.mean()

np.float64(0.5953420669577875)

In [199]:
df_full_train[(df_full_train.tenure >= 2) & (df_full_train.tenure <= 12)].churn.mean()

np.float64(0.41798107255520506)

In [200]:
df_full_train[df_full_train.tenure > 12].churn.mean()

np.float64(0.17634908339788277)

In [201]:
df_full_train[['tenure']].corrwith(df_full_train.churn)

tenure   -0.351885
dtype: float64

- Churn decreases as tenure grows (negative correlation)

In [202]:
df_full_train[df_full_train.monthlycharges <= 20].churn.mean()

np.float64(0.08795411089866156)

In [203]:
df_full_train[(df_full_train.monthlycharges > 20) & (df_full_train.monthlycharges <= 50)].churn.mean()

np.float64(0.18340943683409436)

In [204]:
df_full_train[df_full_train.monthlycharges > 50].churn.mean()

np.float64(0.32499341585462205)

In [205]:
df_full_train[['monthlycharges']].corrwith(df_full_train.churn)

monthlycharges    0.196805
dtype: float64

- The more people pay monthly, the more likely they are to leave  (positive correlation)

## One-hot encoding

In [206]:
df_full_train.contract.unique()

<StringArray>
['two_year', 'one_year', 'month-to-month']
Length: 3, dtype: str

```python
{"contract": "two_year", "tenure": 72, "monthlycharges": 115.5}

```latex
contract=month-to-month  contract=one_year  contract=two_year  tenure  monthlycharges
                      0                  0                  1      72           115.5

- Only one of the contract columns is "hot" (set to 1)

| Gender | Contract | `gender=F` | `gender=M` | `contract=M` | `contract=1Y` | `contract=2Y` |
|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
| F | 2Y | 1 | 0 | 0 | 0 | 1 |
| F | 1Y | 1 | 0 | 0 | 1 | 0 |
| M | M | 0 | 1 | 1 | 0 | 0 |
| M | 1Y | 0 | 1 | 0 | 1 | 0 |
| F | 1Y | 1 | 0 | 0 | 1 | 0 |
| M | M | 0 | 1 | 1 | 0 | 0 |
| M | 2Y | 0 | 1 | 0 | 0 | 1 |

In [207]:
dicts = df[categorical + numerical].to_dict(orient='records')

In [208]:
dicts[0]

{'gender': 'female',
 'seniorcitizen': 0,
 'partner': 'yes',
 'dependents': 'no',
 'phoneservice': 'no',
 'multiplelines': 'no_phone_service',
 'internetservice': 'dsl',
 'onlinesecurity': 'no',
 'onlinebackup': 'yes',
 'deviceprotection': 'no',
 'techsupport': 'no',
 'streamingtv': 'no',
 'streamingmovies': 'no',
 'contract': 'month-to-month',
 'paperlessbilling': 'yes',
 'paymentmethod': 'electronic_check',
 'tenure': 1,
 'monthlycharges': 29.85,
 'totalcharges': 29.85}

In [209]:
from sklearn.feature_extraction import DictVectorizer

dv = DictVectorizer(sparse=False)

train_dict = df_train[categorical + numerical].to_dict(orient='records')
# dv.fit(train_dict)
# X_train = dv.transform(train_dict)
X_train = dv.fit_transform(train_dict) # we only fit vectorizer with train ditctionary

- fit learns the list of categories for each column
- transform turns dictionaries into a matrix

In [210]:
X_train.shape

(4225, 45)

In [211]:
df_train[categorical].nunique().values.sum() + len(numerical)

np.int64(46)

The one-column difference is `seniorcitizen`. Although We list it as categorical, its values are numeric (`0` and `1`). `DictVectorizer` treats numeric dictionary values as a single numeric feature, rather than making two one-hot columns. 

You can see this in `dv.get_feature_names_out()`: it includes `seniorcitizen`, not `seniorcitizen=0` and `seniorcitizen=1`.

In [212]:
dv.get_feature_names_out()

array(['contract=month-to-month', 'contract=one_year',
       'contract=two_year', 'dependents=no', 'dependents=yes',
       'deviceprotection=no', 'deviceprotection=no_internet_service',
       'deviceprotection=yes', 'gender=female', 'gender=male',
       'internetservice=dsl', 'internetservice=fiber_optic',
       'internetservice=no', 'monthlycharges', 'multiplelines=no',
       'multiplelines=no_phone_service', 'multiplelines=yes',
       'onlinebackup=no', 'onlinebackup=no_internet_service',
       'onlinebackup=yes', 'onlinesecurity=no',
       'onlinesecurity=no_internet_service', 'onlinesecurity=yes',
       'paperlessbilling=no', 'paperlessbilling=yes', 'partner=no',
       'partner=yes', 'paymentmethod=bank_transfer_(automatic)',
       'paymentmethod=credit_card_(automatic)',
       'paymentmethod=electronic_check', 'paymentmethod=mailed_check',
       'phoneservice=no', 'phoneservice=yes', 'seniorcitizen',
       'streamingmovies=no', 'streamingmovies=no_internet_service',
       'streamingmovies=yes', 'streamingtv=no',
       'streamingtv=no_internet_service', 'streamingtv=yes',
       'techsupport=no', 'techsupport=no_internet_service',
       'techsupport=yes', 'tenure', 'totalcharges'], dtype=object)

In [213]:
X_train

array([[0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 1.00000e+00,
        7.20000e+01, 8.42515e+03],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        1.00000e+01, 1.02155e+03],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        5.00000e+00, 4.13650e+02],
       ...,
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        2.00000e+00, 1.90050e+02],
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 0.00000e+00,
        2.70000e+01, 7.61950e+02],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        9.00000e+00, 7.51650e+02]], shape=(4225, 45))

In [214]:
val_dict = df_val[categorical + numerical].to_dict(orient='records')
X_val = dv.transform(val_dict)

- for the validation data we reuse the already fitted vectorizer and call only `transform`
- If we called `fit` again on validation:
    - the columns could come out in a different order 
    - or a category that appears only in validation would create a new column.
    - The matrix would no longer match the one the model was trained on.

### Alternative: OneHotEncoder

In [215]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler, OneHotEncoder

- prepare the numerical variables

In [216]:
X_train_num = df_train[numerical].values

scaler = StandardScaler()
# scaler = MinMaxScaler()

X_train_num = scaler.fit_transform(X_train_num)

- The scaler scales the numerical features

- Compare the un-scaled version of `tenure` (`numerical[0]`) with the scaled one:

In [220]:
df_train.tenure.values

array([72, 10,  5, ...,  2, 27,  9], shape=(4225,))

In [221]:
X_train_num[:, 0]

array([ 1.6217693 , -0.900001  , -1.10336957, ..., -1.22539072,
       -0.20854785, -0.94067471], shape=(4225,))

- process categorical features

In [226]:
ohe = OneHotEncoder(sparse_output=False, handle_unknown='ignore')

In [227]:
X_train_cat = ohe.fit_transform(df_train[categorical].values)

In [229]:
ohe.get_feature_names_out()

array(['x0_female', 'x0_male', 'x1_0', 'x1_1', 'x2_no', 'x2_yes', 'x3_no',
       'x3_yes', 'x4_no', 'x4_yes', 'x5_no', 'x5_no_phone_service',
       'x5_yes', 'x6_dsl', 'x6_fiber_optic', 'x6_no', 'x7_no',
       'x7_no_internet_service', 'x7_yes', 'x8_no',
       'x8_no_internet_service', 'x8_yes', 'x9_no',
       'x9_no_internet_service', 'x9_yes', 'x10_no',
       'x10_no_internet_service', 'x10_yes', 'x11_no',
       'x11_no_internet_service', 'x11_yes', 'x12_no',
       'x12_no_internet_service', 'x12_yes', 'x13_month-to-month',
       'x13_one_year', 'x13_two_year', 'x14_no', 'x14_yes',
       'x15_bank_transfer_(automatic)', 'x15_credit_card_(automatic)',
       'x15_electronic_check', 'x15_mailed_check'], dtype=object)

- here we forced encoder to consider the `seniorcitizen` feature as categorical variable. (`'x1_0'`, `'x1_1'`)
- in totall 46 columns

- combine two matrices into one

In [230]:
ohe_X_train = np.column_stack([X_train_num, X_train_cat])

In [231]:
ohe_X_train.shape

(4225, 46)

In [233]:
ohe_X_train.round(2)

array([[ 1.62,  1.69,  2.73, ...,  0.  ,  1.  ,  0.  ],
       [-0.9 ,  1.02, -0.55, ...,  0.  ,  1.  ,  0.  ],
       [-1.1 ,  0.37, -0.82, ...,  0.  ,  1.  ,  0.  ],
       ...,
       [-1.23,  0.85, -0.92, ...,  1.  ,  0.  ,  0.  ],
       [-0.21, -1.33, -0.66, ...,  0.  ,  1.  ,  0.  ],
       [-0.94,  0.54, -0.67, ...,  0.  ,  1.  ,  0.  ]], shape=(4225, 46))